/* Localized strings contents for default localized contents */ 

TIZEN_L10N=
{
	"MAIN_MENU_RADAR" : "Radar",
	"MAIN_MENU_WEATHER" : "Weather",
	"MAIN_MENU_COMPASS" : "Compass",
	"MAIN_MENU_ALERTS" : "Alerts",
	"MAIN_MENU_SETTINGS" : "Settings",
	"SETTINGS_MENU_UNITS" : "Units",
	"SETTINGS_MENU_INFORMATION" : "Information",
	"SETTINGS_MENU_UNITS_TIME" : "Time",
	"SETTINGS_MENU_UNITS_DISTANCE" : "Distance",
	"SETTINGS_MENU_UNITS_MAPZOOM" : "Map zoom",
	"SETTINGS_MENU_UNITS_TEMPERATURE" : "Temperature",
	"SETTINGS_MENU_UNITS_TIME_SYSTEM" : "System (default)",
	"SETTINGS_MENU_UNITS_TIME_12h" : "12h",
	"SETTINGS_MENU_UNITS_TIME_24h" : "24h",	
	"SETTINGS_MENU_UNITS_DISTANCE_MILES_DEFAULT" : "Miles (default)",
	"SETTINGS_MENU_UNITS_DISTANCE_KILOMETERS" : "Kilometers",
	"SETTINGS_MENU_UNITS_DISTANCE_MEGAMETERS" : "Megameters",
	"SETTINGS_MENU_INFORMATION_APP_VERSION" : "Version",
	"SETTINGS_MENU_UNITS_MAP_ZOOM_MILES" : "miles",
	"SETTINGS_MENU_UNITS_MAP_ZOOM_KILOMETERS" : "kilometers",
	"SETTINGS_MENU_UNITS_MAP_ZOOM_MEGAMETERS" : "megameters",
	
};
